C_COMPILE ?= arm-linux-gnueabihf-gcc
CC_COMPILE ?= arm-linux-gnueabihf-g++

c_objects = led_test.o

buildout = led_test

run_dist = /home/lrq/linux/nfs/qtrootfs/home/module_test

ENV_PATH_ROOT := /home/lrq/Desktop/IMXControl

include $(ENV_PATH_ROOT)/scripts/build/build_exe.mk

